name: Deploy static content to Pages

on:
  # Trigger workflow on push to the main branch
  push:
    branches: ["main"]

  # Allow manual trigger from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # Upload the HTML file(s)
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # This assumes your index.html is at the root of the repository

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
